### PR TITLE
Use config and install files in .ci dir of ngic repo

### LINKED ISSUE #21: Remove local copy of *.cfg, *.json and *.conf files
Working configuration reference of OMEC is taken as a backup and restored each time on Jenkins job execution. This would replace the freshly cloned configuration files from all repos on the Jenkins workspace.
If a patch is applied on one of these configuration files in OMEC, Jenkins would not consider those files for regression tests.

Affected files:
- [x] NGIC
interface.cfg / cp_config.cfg / dp_config.cfg / static_arp.cfg
cp-auto-install-options.txt  / dp-auto-install-options.txt

- [x] MME
mme.json / s1ap.json / s11.json / s6a.json / s6a_fd.conf

- [x] c3po/HSS
hss.json
 
- [x] c3po SGX Dealer
dealer-in.json / dealer-out.json / kms.json / cdf.conf / ctf.json

### PR DESCRIPTION
**Pull request by micpez**
Use configuration and install files stored in .ci directory
of ngic-rtc repo, instead of handling configurations of CP/DP with local
files.

partially addresses #21
for NGIC

### CODE REVIEW

**Comment by krsna1729** [comment]
@micpez change the keyword to partially addresses. otherwise it will close the issue :P

**Comment by krsna1729** [comment]
Whatever shell commands you are running here, can we make them a script and add to https://github.com/omec-project/ngic-rtc/pull/72

**Comment by micpez** [comment]
> Whatever shell commands you are running here, can we make them a script and add to [omec-project/ngic-rtc#72](https://github.com/omec-project/ngic-rtc/pull/72)

I think it is better if we do one step at a time.

**Comment by micpez** [comment]
This can be merged only after https://github.com/omec-project/ngic-rtc/pull/72 is merged.

**Comment by micpez** [comment]
rebased

**Comment by krsna1729** [comment]
@micpez can we merge these here and test the outstanding PR in ngic?

**Comment by micpez** [comment]
@sai if you want, please squash and merge. If PR at ngic does not work, we'll have to revert this or CI will not work any longer. Or we can do the opposite, as PR at NGIC is only creation of files in .ci folder with no impact on CI until this PR is merged.

**Pull request merged**
