### PR TITLE
update install-vnf files and test cases

### PR DESCRIPTION
**Pull request by micpez**
Update files to clone repos and install vnfs.

### CODE REVIEW

**Comment by krsna1729** [comment]
@micpez Is there a documentation/diagram to understand whats happening in this file?

**Comment by krsna1729** [comment]
Also, should we make a `.ci/<ci-name>/<component>` folder in each repo to contain all the configuration files and scripts the CI would need, already modified, instead of doing a bunch of `sed` and other bash tricks? That way the this repo stays as minimal as possible without too much knowledge of individual EPC components leaking.

@micpez @zdw WDYT?

**Comment by micpez** [comment]
> 
> 
> @micpez Is there a documentation/diagram to understand whats happening in this file?

These files follow the steps described in the repo install/readme files

> 
> 
> Also, should we make a `.ci/<ci-name>/<component>` folder in each repo to contain all the configuration files and scripts the CI would need, already modified, instead of doing a bunch of `sed` and other bash tricks? That way the this repo stays as minimal as possible without too much knowledge of individual EPC components leaking.
> 
> @micpez @zdw WDYT?
The sed parts are needed because the information will be available only during installation. It is not possible to hard code the value in advance.

**Comment by omecproject** [comment]
@krsna1729 The traditional way we've split up the CI jobs is that unit or self contained tests are put inside a the code repo (a developer would run `make test` or similar commands), but integration tests that build/run the code in a way that is specific to the test environment and test runners are kept in a separate repo that can be maintained as that environment changes.

From my perspective @micpez 's tests here are of the integration type, so keeping them separate is better for now.

**Comment by pingping-lin** [comment]
@omecproject who is the person use this account?

**Pull request merged**
