### PR TITLE
Collect and upload logs and pcaps in container-based jobs

### PR DESCRIPTION
**Pull request by yoooou**

### CODE REVIEW

**Comment by krsna1729** [comment]
@yoooou please add below output to omec/k8s-logs artifact list.

```
kubectl apply view-last-applied pod <name> -o yaml
```

**Comment by yoooou** [comment]
> @yoooou please add below output to omec/k8s-logs artifact list.
> 
> ```
> kubectl apply view-last-applied pod <name> -o yaml
> ```

@krsna1729 Sure. This command doesn't seem to be giving any output though

**Comment by krsna1729** [comment]
@yoooou hmm... then 

```
kubectl get pod <name> -o yaml
```

**Comment by yoooou** [comment]
> @yoooou hmm... then
> 
> ```
> kubectl get pod <name> -o yaml
> ```

Please check this build and see if it has all the artifacts you need https://jenkins.opencord.org/job/omec_archive-artifacts_dev/31/

**Comment by krsna1729** [comment]
@yoooou looks good.

**Pull request merged**
